# Generated by Django 2.0 on 2020-10-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uphone', models.IntegerField(verbose_name='手机')),
                ('upwd', models.CharField(max_length=30, verbose_name='密码')),
                ('uname', models.CharField(max_length=50, verbose_name='名字')),
                ('uemail', models.EmailField(max_length=254, null=True, verbose_name='邮箱')),
                ('isActive', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
