# Generated by Django 2.0 on 2020-10-13 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uphone',
            field=models.CharField(max_length=11, verbose_name='手机'),
        ),
    ]
